#JDBC Properties

spring.datasource.url=jdbc:mysql://localhost:3306/employee_directory
spring.datasource.username=springnew
spring.datasource.password=springnew

# Configure Custom path for OpenAPI and Swagger

# springdoc.swagger-ui.path=/my-ui.html

# Cofigure custom paths for api docs

# springdoc.api-docs.path=/my-api-docs



